# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('faculty', models.CharField(max_length=4, primary_key=True)),
                ('classnum', models.CharField(db_column='classNum', max_length=4, primary_key=True)),
                ('term', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassRequiresEquipment',
            fields=[
                ('faculty', models.CharField(max_length=4, primary_key=True)),
                ('classnum', models.CharField(db_column='classNum', max_length=4, primary_key=True)),
                ('term', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('equipmentid', models.IntegerField(db_column='equipmentID', primary_key=True)),
            ],
            options={
                'db_table': 'ClassRequiresEquipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfirmedTrade',
            fields=[
                ('tradeid', models.IntegerField(db_column='tradeID', primary_key=True, serialize=False)),
                ('dateconfirmed', models.DateTimeField(db_column='dateConfirmed')),
            ],
            options={
                'db_table': 'ConfirmedTrade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipmentid', models.IntegerField(db_column='equipmentID', primary_key=True, serialize=False)),
                ('equipmentname', models.CharField(db_column='equipmentName', max_length=128)),
                ('equipmenttype', models.CharField(db_column='equipmentType', max_length=3)),
            ],
            options={
                'db_table': 'Equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pwhash', models.TextField()),
                ('faculty', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=12)),
            ],
            options={
                'db_table': 'Instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PendingTrade',
            fields=[
                ('tradeid', models.IntegerField(db_column='tradeID', primary_key=True, serialize=False)),
                ('requestusername', models.CharField(db_column='requestUsername', max_length=32)),
                ('responseusername', models.CharField(db_column='responseUsername', max_length=32)),
                ('requestequipid', models.IntegerField(db_column='requestEquipID')),
                ('responseequipid', models.IntegerField(db_column='responseEquipID')),
                ('daterequested', models.DateTimeField(db_column='dateRequested')),
            ],
            options={
                'db_table': 'PendingTrade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pwhash', models.TextField()),
                ('year', models.IntegerField()),
                ('faculty', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=12)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentHasEquipment',
            fields=[
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='swapapp.Student')),
                ('equipmentid', models.IntegerField(db_column='equipmentID', primary_key=True)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentHasEquipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTakesClass',
            fields=[
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='swapapp.Student')),
                ('faculty', models.CharField(max_length=4, primary_key=True)),
                ('classnum', models.CharField(db_column='classNum', max_length=4, primary_key=True)),
                ('term', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'StudentTakesClass',
                'managed': False,
            },
        ),
    ]
